// refs/components/top-bar.tsx
"use client"

import Link from "next/link"
import { CircleHelp, Moon, Sun } from "lucide-react"
import { usePathname } from "next/navigation"
import { useEffect, useState } from "react"

const links = [
  ["Workspace", "/"],
  ["Catalog", "/easy-png-tools/list-tools"],
  ["Gradient", "/easy-png-tools/gradient"],
  ["Background remover", "/easy-png-tools/background-remover"],
] as const

export function TopBar({ section = "WORKSPACE", status = "LOCAL MODE / READY" }: { section?: string; status?: string }) {
  const pathname = usePathname()
  const [dark, setDark] = useState(false)

  useEffect(() => {
    const stored = window.localStorage.getItem("ep-theme")
    const isDark = stored === "dark"
    setDark(isDark)
    document.documentElement.classList.toggle("dark-mode", isDark)
  }, [])

  const toggleTheme = () => {
    const next = !dark
    setDark(next)
    document.documentElement.classList.toggle("dark-mode", next)
    window.localStorage.setItem("ep-theme", next ? "dark" : "light")
  }

  return <header className="topbar"><Link href="/" className="brand"><span className="brand-mark">EP</span><span>easy-png-tools</span><span className="version">/ {section}</span></Link><nav className="top-nav" aria-label="Primary navigation">{links.map(([label, href]) => <Link key={href} className={pathname === href ? "active" : ""} href={href}>{label}</Link>)}</nav><div className="top-actions"><span className="status"><i /> {status}</span><button className="icon-btn" aria-label="Help"><CircleHelp size={17} /></button><button className="icon-btn" aria-label="Toggle theme" onClick={toggleTheme}>{dark ? <Sun size={17} /> : <Moon size={17} />}</button><div className="language"><button className="active">RU</button><span>/</span><button>EN</button></div></div></header>
}

export default TopBar

// web/src/lib/components/kit/TopBar.svelte
<script lang="ts">
	import IconButton from "./IconButton.svelte";
	import StatusDot from "./StatusDot.svelte";
	import { resolve } from "$app/paths";
	import { CircleHelp, Moon, Sun } from "@lucide/svelte";

	interface Props {
		theme: "light" | "dark";
		crumb?: string;
		ontoggle: () => void;
	}

	let { theme, crumb, ontoggle }: Props = $props();

	let lang = $state("RU");
</script>

	<header class="topbar">
		<div class="brand">
			<span class="brand-mark">EP</span>
			<span>easy-png-tools</span>
			{#if crumb}<span class="version">{crumb}</span>{/if}
		</div>
		<nav class="nav">
			<a href={resolve("/preview/demo")}>Workspace</a>
			<a href={resolve("/preview/list-tools")}>Catalog</a>
			<a href={resolve("/preview/tools/linear-gradient-png")}>Gradient</a>
			<a href={resolve("/preview/tools/remove-background-png")}>Background remover</a>
		</nav>
		<div class="top-actions">
		<span class="status"><StatusDot /> AUTO PIPELINE</span>
		<IconButton
			icon={CircleHelp}
			label="Help"
			variant="bare"
			onclick={() => {}}
		/>
		<IconButton
			icon={theme === "light" ? Moon : Sun}
			label="Toggle theme"
			variant="bare"
			onclick={ontoggle}
		/>
		<div class="lang" role="group" aria-label="Language">
			<button
				type="button"
				class="lang-btn"
				class:active={lang === "RU"}
				onclick={() => (lang = "RU")}>RU</button
			>
			<button
				type="button"
				class="lang-btn"
				class:active={lang === "EN"}
				onclick={() => (lang = "EN")}>EN</button
			>
		</div>
	</div>
</header>

<style>
	.topbar {
		position: sticky;
		top: 0;
		z-index: 20;
		display: flex;
		justify-content: space-between;
		align-items: center;
		height: 64px;
		padding: 0 clamp(20px, 4vw, 64px);
		background: var(--panel);
		border-bottom: 1px solid var(--line);
	}
	.brand {
		display: flex;
		align-items: center;
		gap: 10px;
		font: 600 14px var(--font-mono);
		color: var(--foreground);
	}
	.brand-mark {
		background: var(--blue);
		color: #fff;
		width: 30px;
		height: 30px;
		font-size: 11px;
		display: grid;
		place-items: center;
	}
	.version {
		font: 10px var(--font-mono);
		letter-spacing: 0.12em;
		color: var(--blue);
	}
	.nav {
		display: flex;
		align-items: center;
		gap: 18px;
		margin-left: 24px;
	}
	.nav a {
		color: var(--muted);
		font: 12px var(--font-mono);
		letter-spacing: 0.04em;
		text-decoration: none;
	}
	.nav a:hover {
		color: var(--foreground);
	}
	.top-actions {
		display: flex;
		align-items: center;
		gap: 16px;
	}
	.status {
		display: flex;
		align-items: center;
		gap: 7px;
		color: var(--muted);
		font: 10px var(--font-mono);
		letter-spacing: 0.08em;
	}
	.lang {
		display: inline-flex;
		border: 1px solid var(--line);
		border-radius: var(--radius);
		overflow: hidden;
	}
	.lang-btn {
		border: 0;
		background: transparent;
		color: var(--muted);
		font: 10px var(--font-mono);
		letter-spacing: 0.06em;
		padding: 6px 9px;
		cursor: pointer;
	}
	.lang-btn + .lang-btn {
		border-left: 1px solid var(--line);
	}
	.lang-btn.active {
		background: var(--foreground);
		color: var(--background);
	}
</style>
